version: '3'
services:
    db:
        build: 
            context: ./db
        environment: 
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - "3306:3306"
        networks:
            default:
                aliases:
                    - db
networks:
    default:
        driver: bridge