\W

CREATE INDEX X_MRCONSO_CUI ON MRCONSO(CUI);

CREATE INDEX X_MRCONSO_CODE ON MRCONSO(CODE);

CREATE INDEX X_MRCONSO_SAB_TTY ON MRCONSO(SAB,TTY);

CREATE INDEX X_MRCONSO_STR ON MRCONSO(STR(255));

CREATE INDEX X_MRREL_CUI1 ON MRREL(CUI1);

CREATE INDEX X_MRREL_CUI2 ON MRREL(CUI2);

CREATE INDEX X_MRREL_SAB ON MRREL(SAB);

CREATE INDEX X_MRSAT_CUI ON MRSAT(CUI);

CREATE INDEX X_MRSAT_SAB ON MRSAT(SAB);

CREATE INDEX X_MRSAT_ATN ON MRSAT(ATN);

CREATE INDEX X_MRSTY_CUI ON MRSTY(CUI);

CREATE INDEX X_MRSTY_STY ON MRSTY(STY);

CREATE INDEX X_MRSTY_TUI_STN_STY ON MRSTY(TUI,STN,STY);

CREATE INDEX X_MRAUI_CUI2 ON MRAUI(CUI2);

CREATE INDEX X_MRCUI_CUI2 ON MRCUI(CUI2);
